/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author victo
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnClientes = new javax.swing.JMenu();
        mnFornecedor = new javax.swing.JMenu();
        mnFuncionario = new javax.swing.JMenu();
        mnUnidade = new javax.swing.JMenu();
        mnVeiculos = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1148, 639));

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenuBar1.setMinimumSize(new java.awt.Dimension(94, 50));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(94, 40));

        mnClientes.setText("Clientes");
        mnClientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnClientesMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnClientes);

        mnFornecedor.setText("Fornecedor");
        mnFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnFornecedorMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnFornecedor);

        mnFuncionario.setText("Funcionario");
        mnFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnFuncionarioMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnFuncionario);

        mnUnidade.setText("Unidade");
        mnUnidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnUnidadeMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnUnidade);

        mnVeiculos.setText("Veiculos");
        mnVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnVeiculosMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnVeiculos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnClientesMouseClicked
        FrmClientes frmClientes = new FrmClientes();
        frmClientes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnClientesMouseClicked

    private void mnFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnFornecedorMouseClicked
        FrmFornecedor frmFornecedor = new FrmFornecedor();
        frmFornecedor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnFornecedorMouseClicked

    private void mnFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnFuncionarioMouseClicked
        FrmFuncionario frmFuncionario = new FrmFuncionario();
        frmFuncionario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnFuncionarioMouseClicked

    private void mnUnidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnUnidadeMouseClicked
        FrmUnidade frmUnidade = new FrmUnidade();
        frmUnidade.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnUnidadeMouseClicked

    private void mnVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnVeiculosMouseClicked
        FrmVeiculos frmVeiculos = new FrmVeiculos();
        frmVeiculos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnVeiculosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnClientes;
    private javax.swing.JMenu mnFornecedor;
    private javax.swing.JMenu mnFuncionario;
    private javax.swing.JMenu mnUnidade;
    private javax.swing.JMenu mnVeiculos;
    // End of variables declaration//GEN-END:variables
}
